---
title: "Get and clean data"
output: 
  html_document:
    theme: darkly
date: "2024-11-08"
---

```{r, warning=FALSE, message=FALSE}
library(data.table)
library(tidyverse)
library(openxlsx)
library(arrow)
```   



## IMD

```{r}
url <- # UTLA IMD summaries URL
  "https://assets.publishing.service.gov.uk/media/5d8b3d7aed915d0369518030/File_11_-_IoD2019_Local_Authority_District_Summaries__upper-tier__.xlsx"

imd <-
read.xlsx(xlsxFile = url, sheet = "IMD") |>
  janitor::clean_names()

imd |> 
  select(upper_tier_local_authority_district_code_2019, upper_tier_local_authority_district_name_2019, imd_average_score) |>
  mutate(imd_decile = ntile(imd_average_score, 10)) |> 
  write_csv("data/raw/utla_imd_decile.csv")

```

## Drug poisoning deaths

This file is NDTMS-ONS data linkage; received by email from Stefan and named `table1_all deaths_Cocaine version 1.xlsx`

```{r}
df <- # Load deaths data
  openxlsx::read.xlsx("data/raw/table1_all deaths_Cocaine version 1.xlsx", sheet = "table1_all deaths")

write_parquet(df, "data/raw/ndtms_mortality_data.parquet")

# dt <- # Deaths from drug misuse & suspected deaths from drug misuse but not recorded as such
#   dt[(drug_misuse_combined == 0 & Treatment_Status != "no match with NDTMS")| drug_misuse_combined == 1,]
# 
# write_parquet(dt, "data/raw/deaths_related_to_misuse_inc_not_rec.parquet")

```

